[package]
name = "swarm_optimizers"
version = "0.1.0"
edition = "2021"

[workspace]
members = ["stat_collector"]


[dependencies]
rand = "0.8"
GSL = "7"
rand_distr = "0.4"
clap = { version = "4", features = ["derive"] }
num_cpus = "1"
